#!/bin/bash
##########################################################################
clear
set -x
exec 2>&1		# Unify output
IMGSIZE=1500	# Image size in MB

echo "##### $(date) - Starting"
echo "##### $(date) - Creating SD card image"

# Image filename
#image=/tmp/rpi-$$.img
image=/root/sd/rpi-01.img

########
# Create image file, partition it
########
dd if=/dev/zero of=${image} bs=1M count=${IMGSIZE}
echo -e "n\np\n1\n\n+51M\nn\np\n2\n\n\nt\n1\nc\na\n1\np\nw\n" | fdisk ${image}
