#!/bin/bash
##########################################################################
set -x
exec 2>&1		# Unify output

# Image filename
#image=/tmp/rpi-$$.img
image=/root/tmp_sd/rpi-01.img
fsdir=${image}p2

##########################################################################
echo "##### $(date) - Post-installation file configuration"

mount -o bind /proc ${fsdir}/proc
mount -o bind /dev ${fsdir}/dev
mount -o bind /sys ${fsdir}/sys

cp /etc/resolv.conf ${fsdir}/etc/resolv.conf

cat > ${fsdir}/tmp/reinstall << EOF 
#!/bin/bash
echo "Reinstalling within chroot."
yum reinstall -y \$(rpm -qa --qf "%{name}\n"|egrep -v "^setup$")
yum clean all
find / -name '*.rpmsave' -o -name '*.rpmnew' -delete
echo "Finished reinstalling within chroot. Exit status: $?"
EOF

chmod 0755 ${fsdir}/tmp/reinstall

chroot ${fsdir} /tmp/reinstall

rm ${fsdir}/tmp/reinstall ${fsdir}/etc/resolv.conf

# /etc/fstab
cat > $fsdir/etc/fstab << EOF
LABEL="rootfs"          /                       ext4    defaults,noatime                 1 1
LABEL="boot"            /boot                   vfat    noauto,comment=systemd.automount 1 2
EOF

# /etc/hosts
cat > $fsdir/etc/hosts << EOF
127.0.0.1       localhost localhost.localdomain raspi.local
EOF

# password for root (password=raspberrypi)
sed -i 's|root:.*:|root:$6$KW0GGbE5$zlEB9.PbHVh8kmXj1WMFGLJGwwthhU4oXn2oNxHZllbUSzTsVhTZ9jts8RC7uicuUCWyrsZ1e2yEj4ErDLOHQ/:15525:0:99999:7:::|' $fsdir/etc/shadow

# Disable SELINUX
sed -i 's/^SELINUX=.*$/SELINUX=disabled/g'    ${fsdir}/etc/selinux/config

# hostname
cat > ${fsdir}/etc/sysconfig/network << EOF
NETWORKING=yes
HOSTNAME=raspi.local
NETWORKWAIT=1
EOF

# default network configuration (dhcp)
cat > $fsdir/etc/sysconfig/network-scripts/ifcfg-eth0 << EOF
DEVICE=eth0
BOOTPROTO=dhcp
ONBOOT=yes
NM_CONTROLLED=yes
EOF

# i18n settings
cat > ${fsdir}/etc/sysconfig/i18n << EOF
LANG="en_US.UTF-8"
SYSFONT="latarcyrheb-sun16"
EOF

umount ${fsdir}/proc/
umount ${fsdir}/dev/
umount ${fsdir}/sys/

