#!/bin/bash
##########################################################################
set -x
exec 2>&1 # Unify output

# Image filename
#image=/tmp/rpi-$$.img
image=/root/sd/rpi-01.img
fsdir=${image}p2

##########################################################################
echo "##### $(date) - Installing packages"

# Install packages into image
yum clean all
yum install -y \
    --disablerepo=\* \
    --enablerepo=rpi-remix \
    --enablerepo=rpi-fedora \
    --enablerepo=rpi-fedora-updates \
    --enablerepo=denix-x \
    --installroot="$fsdir" \
    -x fedora-release \
    -x fedora-release-notes \
    -x fedora-logos \
    -x generic-release \
    -x system-config-date \
    -x kernel \
    -x firstboot \
    -x xorg-x11-drv-ati \
    -x xorg-x11-drv-cirrus \
    -x xorg-x11-drv-geode \
    -x xorg-x11-drv-intel \
    -x xorg-x11-drv-mga \
    -x xorg-x11-drv-nouveau \
    -x xorg-x11-drv-omap \
    -x xorg-x11-drv-qxl \
    -x xorg-x11-drv-vesa \
    -x xorg-x11-drv-vmware \
    -x smolt \
    -x smolt-firstboot \
    -x kernel-kirkwood \
    -x ConsoleKit \
    -x kernel-imx \
    -x plymouth \
    -x abrt* \
    -x nfs-utils \
    -x talk \
    -x yp-tools \
    -x ypbind \
    -x coolkey \
    raspberrypi-fedora-remix-logos \
    raspberrypi-release \
    raspberrypi-vc-firmware \
    raspberrypi-release-notes \
    raspberrypi-rootfs-resize \
    raspberrypi-kernel \
    raspberrypi-system-config-date \
    raspberrypi-config \
    raspberrypi-firstboot \
    raspberrypi-vc-static \
    denix-bash \
    denix-colors \
    denix-prompt \
    denix-umask \
    @base \
    @core \
    @hardware-support \
    rpm \
    mc \
    xorg-x11-server-Xorg \
    mesa-dri-drivers \
    libbcm2835 \
    pi3d
