#!/bin/bash
##########################################################################
set -x
exec 2>&1		# Unify output

# Image filename
#image=/tmp/rpi-$$.img
image=/root/sd/rpi-01.img
#image=/home/it1/sd/rpi-01.img
fsdir=${image}p2

##########################################################################
echo "##### $(date) - Unmount filesystems"

# Unmount filesystems
umount ${fsdir}/proc/
umount ${fsdir}/dev/
umount ${fsdir}/sys/
umount ${image}p2/boot
umount ${image}p2
rmdir  ${image}p2

# Delete image devmappings
kpartx -dv $image

echo "##### $(date) - Finished"
