#!/bin/bash
##########################################################################
clear
set -x
exec 2>&1		# Unify output

echo "##### $(date) - Starting"
echo "##### $(date) - Creating SD card image"

# Image filename
#image=/tmp/rpi-$$.img
image=/root/sd/rpi-01.img
#image=/home/it1/sd/rpi-01.img

# Create image devmappings
kpartx -av ${image}

# Get partitions and make them accessible via loopback+dm
losetup -a
loopback=$( losetup -a | grep "$image" | cut -d":" -f1 | xargs -I {} basename {} )

#######
# Create filesystems
#######
mkfs -t vfat -n boot   /dev/mapper/${loopback}p1
mkfs -t ext4 -L rootfs /dev/mapper/${loopback}p2

# Mount filesystems
fsdir=${image}p2
mkdir -p ${fsdir}
mount -o rw /dev/mapper/${loopback}p2 ${fsdir}
mkdir -p ${fsdir}/boot
mount -o rw /dev/mapper/${loopback}p1 ${fsdir}/boot

# Bind-mount system/kernel filesystems
mkdir -p ${fsdir}/{proc,dev,sys}
mknod ${fsdir}/dev/console c 5 1
mknod ${fsdir}/dev/null c 1 3
mknod ${fsdir}/dev/zero c 1 5
mount -o bind /proc ${fsdir}/proc/
mount -o bind /dev  ${fsdir}/dev/
mount -o bind /sys  ${fsdir}/sys

# Create system directories
mkdir -p ${fsdir}/var/lib/yum
mkdir -p ${fsdir}/var/log
mkdir -p ${fsdir}/etc

